# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            sudo apt-get install -y wget
            wget https://repo.anaconda.com/archive/Anaconda3-2019.10-Linux-x86_64.sh -O anaconda3.sh
            bash anaconda3.sh -b -p "$HOME"/anaconda3
            source /home/circleci/anaconda3/etc/profile.d/conda.sh
            conda activate base
            # Conda configuration
            conda config --set always_yes yes --set auto_update_conda false
            # Update conda
            conda update conda
            # Create test environment
            conda create -n test python=$PYTHON_VERSION
            conda activate test

            # PyTorch and scikit learn
            conda install pytorch torchvision -c pytorch
            conda install scikit-learn

            #gym atari
            pip install 'gym[atari]'

            # Baselines for Atari preprocessing
            # Tensorflow is a dependency, but you don't need to install the GPU version
            conda install tensorflow
            pip install git+git://github.com/openai/baselines

            # pytorch-a2c-ppo-acktr for RL utils
            pip install git+git://github.com/ankeshanand/pytorch-a2c-ppo-acktr-gail

            # Clone and install our package
            pip install -r requirements.txt
            pip install git+git://github.com/mila-iqia/atari-representation-learning.git

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!

      - run:
          name: run tests
          command: |
            source /home/circleci/anaconda3/etc/profile.d/conda.sh
            conda activate test
            conda --version
            python -m scripts.run_probe --method infonce-stdim --env-name PongNoFrameskip-v4

      - store_artifacts:
          path: test-reports
          destination: test-reports